import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ClientLayout from "../app/clientLayout"

const roboto = Roboto({
    subsets: ['latin'],
    weight: ["300", "400", "500", "700"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientLayout>
      <body className={`${roboto.className}`}>
          <div className="root">{children}</div>
      </body>
      </ClientLayout>
    </html>
  );
}
